In [100]:
import numpy as np
import pandas as pd

In [101]:
# question 1
a=np.array([1,2,3,4,5,6,7,8,9,10])
b=np.array([10,9,8,7,6,5,4,3,2,1])
print(np.greater(a,b),'\n')
print(np.less(a,b),'\n')
print(np.equal(a,b),'\n')
print(np.greater_equal(a,b),'\n')
print(np.less_equal(a,b),'\n')


[False False False False False  True  True  True  True  True] 

[ True  True  True  True  True False False False False False] 

[False False False False False False False False False False] 

[False False False False False  True  True  True  True  True] 

[ True  True  True  True  True False False False False False] 



In [102]:
# question 2 Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives

print(np.zeros(10),'\n')
print(np.ones(10),'\n')
print(np.full((1,11),'5'),'\n')
print(np.ones(10)*5,'\n')

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 

[['5' '5' '5' '5' '5' '5' '5' '5' '5' '5' '5']] 

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.] 



In [103]:
# Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of a
# given array

x=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.sum(x))
c=x.ndim
for i in range(c+1):    #+1 as the dimensions start from one and end at n but the rangea function ends at n-1 
    print(np.sum(x[i]))
    

45
6
15
24


In [104]:
# Write a NumPy program to add, subtract, multiply, divide arguments element-wise
a=np.array([1,2,3,4,5,6,7,8,9,10])
b=np.array([10,9,8,7,6,5,4,3,2,1])
print(np.add(a,b),'\n')
print(np.subtract(a,b),'\n')
print(np.multiply(a,b),'\n')
print(np.divide(a,b),'\n')


[11 11 11 11 11 11 11 11 11 11] 

[-9 -7 -5 -3 -1  1  3  5  7  9] 

[10 18 24 28 30 30 28 24 18 10] 

[ 0.1         0.22222222  0.375       0.57142857  0.83333333  1.2
  1.75        2.66666667  4.5        10.        ] 



In [105]:
# Write a NumPy program to compute the trigonometric sine, cosine and tangent array of angles given in degree.
x=[0,15,30,45,60,75,90,105,120,135,150,165,180]
print(np.cos(x),'\n')
print(np.sin(x),'\n')
print(np.tan(x),'\n')

[ 1.         -0.75968791  0.15425145  0.52532199 -0.95241298  0.92175127
 -0.44807362 -0.24095905  0.81418097 -0.99608784  0.69925081 -0.06633694
 -0.59846007] 

[ 0.          0.65028784 -0.98803162  0.85090352 -0.30481062 -0.38778164
  0.89399666 -0.97053528  0.58061118  0.08836869 -0.71487643  0.99779728
 -0.80115264] 

[  0.          -0.8559934   -6.4053312    1.61977519   0.32004039
  -0.42070095  -1.99520041   4.02780176   0.71312301  -0.08871576
  -1.02234624 -15.04135305   1.33869021] 



In [106]:
# Write a Pandas program to create and display a DataFrame from a specified dictionary data which has the index labels
import pandas as pd
import numpy as np

avg_data  = {'name':['abhishek','akash','allwyn','ankith','chandan','chethan','darshan','gagan','gaurav','guru dutt']
             ,'score1':['70','78','64','80','88','79','89','60','50','95'],'score2':['75','88','64','80','95','83','89','60','68','95']}
roll_number = ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10']

final = pd.DataFrame(avg_data , index=roll_number)
print(final,'\n\n')
# print(final[['name','score2']])

         name score1 score2
1    abhishek     70     75
2       akash     78     88
3      allwyn     64     64
4      ankith     80     80
5     chandan     88     95
6     chethan     79     83
7     darshan     89     89
8       gagan     60     60
9      gaurav     50     68
10  guru dutt     95     95 




In [107]:
# Write a Pandas program to select the 'name' and 'score' columns from the following DataFrame.
avg_data  = {'name':['abhishek','akash','allwyn','ankith','chandan','chethan','darshan','gagan','gaurav','guru dutt']
             ,'score1':['70','78','64','80','88','79','89','60','50','95'],'score2':['75','88','64','80','95','83','89','60','68','95']}
roll_number = ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10']

final = pd.DataFrame(avg_data , index=roll_number)
# print(final,'\n\n')
print(final[['name','score2']])

         name score2
1    abhishek     75
2       akash     88
3      allwyn     64
4      ankith     80
5     chandan     95
6     chethan     83
7     darshan     89
8       gagan     60
9      gaurav     68
10  guru dutt     95


In [108]:
# Write a Pandas program to join the two given dataframes along rows and assign all data.
import pandas as pd

avg_data1  = pd.DataFrame({'name':['iron man','batman','hulk','flash','aquaman','daredevil','cap.america','superman','thor','green lanten']
             ,'score1':['70','78','64','80','100','58','89','22','50','95'],'score2':['75','88','64','85','95','83','89','60','68','95']})
# roll_number1 = ['10', '20', '30', '40', '50', '60', '70', '80', '90', '100']

avg_data2  =pd.DataFrame ({'name':['abhishek','akash','allwyn','ankith','chandan','chethan','darshan','gagan','gaurav','guru dutt']
             ,'score1':['70','78','64','80','88','79','89','60','50','95'],'score2':['75','88','64','80','95','83','89','60','68','95']})
# roll_number2 = ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10']

final = pd.concat([avg_data1,avg_data2])
# print(final,'\n\n')
print(final)

           name score1 score2
0      iron man     70     75
1        batman     78     88
2          hulk     64     64
3         flash     80     85
4       aquaman    100     95
5     daredevil     58     83
6   cap.america     89     89
7      superman     22     60
8          thor     50     68
9  green lanten     95     95
0      abhishek     70     75
1         akash     78     88
2        allwyn     64     64
3        ankith     80     80
4       chandan     88     95
5       chethan     79     83
6       darshan     89     89
7         gagan     60     60
8        gaurav     50     68
9     guru dutt     95     95


In [109]:
# Write a Pandas program to detect missing values of a given DataFrame. Display True or False.

pd.set_option('display.max_rows', None)
#pd.set_option('display.max_columns', None)
x= pd.DataFrame({
'serial_number':[1,np.nan,3,4,np.nan,6,np.nan,8,9,10,np.nan,11],
'total_amount':[188.5,128.62,98.25,510.6,151.15,2500,781.25,541.215,543.252,85.25,49.29,69.69],
'purchase_date': ['15-02-1999','26-01-2015',np.nan,'1-1-2020','20-02-1990','21-09-2025','10-05-1988','25-05-1698','15-12-2015','01-01-2000','17-02-1999','05-05-2000'],
'customer_number':[1000,1001,1002,1003,1004,1005,1006,1007,1008,1009,1010,1011],
'salesman_id':[2001,2002,2003,np.nan,2005,2006,2007,np.nan,2008,2009,2010,np.nan]})
print("data frame")
print(x)
print("\n missing values from the data frame")
print(x.isna())



data frame
    serial_number  total_amount purchase_date  customer_number  salesman_id
0             1.0       188.500    15-02-1999             1000       2001.0
1             NaN       128.620    26-01-2015             1001       2002.0
2             3.0        98.250           NaN             1002       2003.0
3             4.0       510.600      1-1-2020             1003          NaN
4             NaN       151.150    20-02-1990             1004       2005.0
5             6.0      2500.000    21-09-2025             1005       2006.0
6             NaN       781.250    10-05-1988             1006       2007.0
7             8.0       541.215    25-05-1698             1007          NaN
8             9.0       543.252    15-12-2015             1008       2008.0
9            10.0        85.250    01-01-2000             1009       2009.0
10            NaN        49.290    17-02-1999             1010       2010.0
11           11.0        69.690    05-05-2000             1011          NaN



In [110]:
# Write a Pandas program to create and display a one-dimensional array-like object containing an array of data.
x=pd.Series([3+6j,2,3,4,5,6,7,8,9,1.02,2.02,3.02])
print('\n')
print(x,'\n')
print(list(x),'\n')
print(type(list(x)))



0     3.000000+6.000000j
1     2.000000+0.000000j
2     3.000000+0.000000j
3     4.000000+0.000000j
4     5.000000+0.000000j
5     6.000000+0.000000j
6     7.000000+0.000000j
7     8.000000+0.000000j
8     9.000000+0.000000j
9     1.020000+0.000000j
10    2.020000+0.000000j
11    3.020000+0.000000j
dtype: complex128 

[(3+6j), (2+0j), (3+0j), (4+0j), (5+0j), (6+0j), (7+0j), (8+0j), (9+0j), (1.02+0j), (2.02+0j), (3.02+0j)] 

<class 'list'>
